"""Create projects table

Revision ID: 6c362fb4f8af
Revises: 
Create Date: 2026-01-10 19:59:22.281354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c362fb4f8af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=500), nullable=False),
    sa.Column('project_group', sa.String(length=200), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=False),
    sa.Column('date_to_client', sa.Date(), nullable=False),
    sa.Column('date_assigned_to_us', sa.Date(), nullable=False),
    sa.Column('internal_deadline', sa.Date(), nullable=True),
    sa.Column('delivery_deadline', sa.Date(), nullable=True),
    sa.Column('assigned_attorney', sa.String(length=200), nullable=False),
    sa.Column('qcp_attorney', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
